export const RAW_CSV_GEMINI = `processed_date,keyword,company,title,date_posted,match_score,matched_skills,gaps_in_skill,job_url,description,location
2026-04-22,data,MS Capital Singapore,Quantitative Researcher / Developer,2026-04-21,85,"Python, SQL, PySpark, Data Ingestion, Data Pipeline Engineering, Machine Learning, Fraud Detection, Financial Modeling, Data Governance","C++, Quant Research, Systematic Trading Strategies, Hedge Fund Experience, Bloomberg/Market Data familiarity",https://www.linkedin.com/jobs/view/4403917008,"MS Capital is a private fund management company with a strong founding team with long-accumulated experience in strategy modelling, trading system and platform development.","Hong Kong"
2026-04-22,data,Hyatt,Business Analytics Intern,,65,"Python, SQL, Power BI, Tableau, Data Analysis, Business Improvement","Direct Business Analytics Experience, Industry-Specific Domain Knowledge",https://www.linkedin.com/jobs/view/4392918454,"Looking to gain real-world experience in business, data, and analytics for 6-months?","Hong Kong"
2026-04-22,data,Zurich Insurance,Intern (Data Engineer),,85,"Python, SQL, PySpark, Databricks, Tableau, Data Pipeline Engineering, Data Governance, Inventory Management & Optimization, Marketing Analytics, Fraud Detection, AML/KYC Compliance","Azure Synapse Analytics, QlikView, Data Lakes",https://www.linkedin.com/jobs/view/4391864611,"As a Data Engineering intern, you will support a variety of data and analytics projects.","Hong Kong"
2026-04-22,data,MTR Corporation Limited 香港鐵路有限公司,Marketing Officer I (Ref:2500015R),,35,"Business Analysis, Marketing Analytics, Financial Modeling, Data Governance, Communication","Marketing Campaign Execution, Advertising Strategy, High Speed Rail Marketing, Public Transport/Infrastructure Sector Knowledge",https://www.linkedin.com/jobs/view/4400480712,"Develop and implement marketing plans for High Speed Rail service as well as other related areas to achieve business targets","Hong Kong"
2026-04-22,data,Laboratoire National de Référence des Bâtiments et Travaux Publics (LNR-BTP),Market Analys / Research Analys/Brand Analys,,75,"Market Research, Data Analysis, Business Analysis, Data Visualization, Statistical Analysis, Tableau, Microsoft Excel","Brand Strategy, Consumer Perception Analysis, Market Share Tracking, Focus Group Moderation",https://www.linkedin.com/jobs/view/4402403116,"We are seeking a detail-oriented and results-driven Market Analyst to join our team.","Hong Kong"
2026-04-22,data,CCB International (Holdings) Limited,Asset Management - Fixed Income Investment,,35,"Python, SQL, Data Analysis","Fixed Income Investing, Credit Research, Fixed Income Market Knowledge",https://www.linkedin.com/jobs/view/4388882565,"Assist in conducting research on fixed income investments.","Hong Kong"
2026-04-22,data,BBVA,IT Support - Corporate and Investment Banking (CIB),,35,"SQL, Python, FastAPI, Docker, Data Governance","Networking fundamentals, Servers management, Cybersecurity fundamentals, ITIL/CCNA/CompTIA certifications",https://www.linkedin.com/jobs/view/4401921895,"We are seeking a highly committed and technically skilled IT Support professional.","Hong Kong"
2026-04-22,fintech,OSL,Future operations Intern,,35,"Data Reporting, Bilingual Support, Operational Support","FinTech Knowledge, Securities Brokerage Experience, Crypto/Finance Domain Knowledge",https://www.linkedin.com/jobs/view/4403908433,"We are looking for a proactive and detail-oriented Future Operations Intern.","Hong Kong"
2026-04-22,fintech,OSL,KOL & Affiliate Business Development Specialist (Hong Kong Market),,35,"Marketing Analytics, Data Governance, SQL, Python, FastAPI, Docker, LangChain, LLM, Scikit-learn, XGBoost","KOL Relationship Development, Affiliate Marketing, Sales Experience, Community Management, Web3/Cryptocurrency Industry Knowledge",https://www.linkedin.com/jobs/view/4404248240,"We are looking for an aggressive, highly motivated KOL & Affiliate Business Development Specialist.","Hong Kong"
2026-04-22,fintech,Wonder,Assistant Product Manager – Transport (Mobility Payments),,65,"Product Communication, Data Analysis and Reporting, Market and User Focus, Cross-departmental Communication abilities","Payment provider integrations, Payment processing, Card acquirers, Online payment gateway integration, Alternative payment methods",https://www.linkedin.com/jobs/view/4403938093,"Wonder is a leading payments gateway and FinTech platform.","Hong Kong"
2026-04-22,fintech,Antalpha,AI Agent Developer Intern,,88,"Python, SQL, Data Pipeline Engineering, AI & Marketing Analytics, Fraud Detection, LLM applications, RAG systems, LangChain, FastAPI, Docker","JavaScript/TypeScript, Claude Code/Codex experience, Prompt Engineering expertise (specific focus), Cloud deployment experience",https://www.linkedin.com/jobs/view/4402403106,"This is not a “shadow and learn” internship. Join as an AI Agent Developer Intern.","Hong Kong"
2026-04-22,fintech,Maverick,"Digital Marketing, Sales & Community Builder",,35,"Python, SQL, Data Governance, Marketing Analytics","Social Media Management, Community Building, SEO, Copywriting, CRM Systems",https://www.linkedin.com/jobs/view/4404225965,"Are you a passionate digital marketer? Join Maverick.","Hong Kong"
2026-04-22,fintech,RedotPay,Chief Financial Officer,,35,"Financial Planning & Analysis (FP&A), Financial Modeling, Tax Planning, Audit, Supply Chain Management, Inventory Management & Optimization, Data Governance","CFO/Senior Finance Executive experience, US GAAP compliance, Transfer Pricing expertise",https://www.linkedin.com/jobs/view/4404942688,"As our CFO, you will lead the financial strategy.","Hong Kong"
2026-04-22,fintech,JRFX Official,Marketing Executive,,25,"Project Management, Vendor Management","Marketing Strategy, Brand Identity Management, Public Relations",https://www.linkedin.com/jobs/view/4403942260,"We are seeking a detail-oriented Marketing Executive.","Hong Kong"
`;

export const RAW_CSV_GPT4 = RAW_CSV_GEMINI.replace(/85/g, '92').replace(/65/g, '78').replace(/35/g, '42');
